#left associativity

>> "PROGRAM BODY"
PROGRAM program sq_op PROGRAMBODY sq_cl
PROGRAMBODY DECLARATION_LIST ASSIGNMENT_LIST
DECLARATION_LIST DECLARATION_STMT DECLARATION_LIST
DECLARATION_LIST DECLARATION_STMT
ASSIGNMENT_LIST ASSIGNMENT_STMT ASSIGNMENT_LIST
ASSIGNMENT_LIST ASSIGNMENT_STMT

>> "DECLARATION STATEMENTS"
DECLARATION_STMT PRIM_DECLARATION_STMT
DECLARATION_STMT RECTARR_DECLARATION_STMT
DECLARATION_STMT JAGGARR_DECLARATION_STMT
>>>>"PRIMITIVE"
PRIM_DECLARATION_STMT declare ID colon PRIM_TYPE semicolon
PRIM_DECLARATION_STMT declare list of variables ID_LIST colon PRIM_TYPE semicolon
ID_LIST ID ID_LIST
ID_LIST ID
PRIM_TYPE integer
PRIM_TYPE real
PRIM_TYPE boolean
>>>> "RECTANGULAR ARRAYS"
RECTARR_DECLARATION_STMT declare ID colon array RANGE_LIST of PRIM_TYPE semicolon
RECTARR_DECLARATION_STMT declare list of variables ID_LIST colon array RANGE_LIST of PRIM_TYPE semicolon
RANGE_LIST RANGE RANGE_LIST
RANGE_LIST RANGE 				#zero dimension case?
RANGE sq_op RANGE_VAL .. RANGE_VAL sq_cl
RANGE_VAL ID
RANGE_VAL const
>>>> "JAGGED ARRAYS"

>> "ASSIGNMENT STATEMENTS"
nvkjdvj